name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main # Or your default branch, e.g., 'master'
  workflow_dispatch: # Allows you to manually trigger the workflow from GitHub Actions tab

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures all history is fetched, important for LFS if you use it
          lfs: true # Enable Git LFS if you have large files

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }} # Access the secret you created
        run: |
          git config --global user.email "ahmad.gaber54@egmail.com" # Replace with your email
          git config --global user.name "AhmadGaber54" # Replace with your GitHub username

          # Replace HF_USERNAME and SPACE_NAME with your actual Hugging Face username and Space name
          git push https://ahmadgaber5474:$HF_TOKEN@huggingface.co/spaces/ahmadgaber5474/flask-web-server-2 main
          # Or 'master' if that's your branch
